name: "ãƒ—ãƒ«ãƒªã‚¯ã‚¨ã‚¹ãƒˆã«å¤‰æ›´å†…å®¹ã®ãƒ©ãƒ™ãƒ«ã‚’ä»˜ã‘ã‚‹"

on:
  pull_request:
    types: [opened]

jobs:
  auto-labeling-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: "ãƒ–ãƒ©ãƒ³ãƒåã‹ã‚‰ãƒ©ãƒ™ãƒ«ã‚’é¸æŠã™ã‚‹"
        id: label_name
        run: |
          branch_type=$(echo ${{github.head_ref}} | cut -d "/" -f1)
          if [ $branch_type == 'feature' ]; then
            label_name=$(echo 'ğŸŒŸfeature')
          elif [ $branch_type == 'fix' ] || [ $branch_type == 'hotfix' ]; then
            label_name=$(echo 'ğŸ•·ï¸bug')
          elif [ $branch_type == 'develop' ]; then
            label_name=$(echo 'ğŸ’release')
          else
            label_name="ğŸ› ï¸fix"
          fi
          echo "::set-output name=label_name::$label_name"

      - name: "ãƒ©ãƒ™ãƒ«ã‚’ä»˜ã‘ã‚‹"
        if: ${{ steps.label_name.outputs.label_name }}
        run: |
          number=$(echo $GITHUB_REF | sed -e 's/[^0-9]//g')
          gh pr edit $number --add-label ${{ steps.label_name.outputs.label_name }}
